image: python:3.5

stages:
  - build
  - test
  - docs
  - deploy

before_script:
  - pip install dist/brest-0.0.1-py3-none-any.whl

build-wheel:
  stage: build
  tags:
    - docker
  before_script:
    - echo
  script:
    - make
  artifacts:
    paths:
      - "dist/*.whl"
    expire_in: 1 week

test-unit:
  stage: test
  tags:
    - docker
  script:
    - python tests/test_colorful_output.py
  dependencies:
    - build-wheel

build-docs:
  stage: docs
  tags:
    - docker
  script:
    - pip install brest[docs]
    - cd docs
    - make html
  artifacts:
    paths:
      - "docs/_build/html/*"
    expire_in: 1 week
  dependencies:
    - build-wheel
