image: python:3.5

stages:
  - build
  - test
  - docs
  - deploy

build-wheel:
  stage: build
  tags:
    - docker
  script:
    - make
    - pip install "dist/*.whl"
  artifacts:
    paths:
      - "dist/*.whl"
    expire_in: 1 week

test-unit:
  stage: test
  tags:
    - docker
  script:
    - python tests/test_output.py

build-docs:
  stage: docs
  tags:
    - docker
  script:
    - pip install sphinx
    - cd docs
    - make html
  artifacts:
    paths:
      - "docs/_build/html/*"
    expire_in: 1 week