image: ${CI_REGISTRY_IMAGE}/toolchain

stages:
  - toolchain
  - build
  - test
  - docs
  - preview
  - deploy

variables:
  IMAGE_TAG: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}'
  PREVIEW_URL: '${CI_COMMIT_REF_SLUG}-${DOC_REVIEW_URL}'
  DOCKER_ENV: '-e GITLAB_SERVER=${CI_SERVER_HOST} -e GITLAB_TOKEN=${GITLAB_TOKEN}'
  ROUTER_ID: '${CI_PROJECT_ID}-${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}'

.rule-deploy-docs:
  if: '$CI_COMMIT_TAG && ($CI_COMMIT_TAG !~ /dev/) && ($CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/)'

.rule-do-not-deploy-doc:
  if: '$CI_COMMIT_TAG && ($CI_COMMIT_TAG !~ /dev/) && ($CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/)'
  when: never

before_script:
  # Change pending to be added to toolchain, cython needed by hidapi
  - pip install Cython
  - pip install dist/brest-*.whl

build-wheel:
  stage: build
  tags:
    - docker
  before_script:
    - echo
  script:
    - make
  artifacts:
    paths:
      - "dist/brest-*.*"
    expire_in: 1 week

publish-toolchain:
  image: docker
  stage: toolchain
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - cd docker
    - docker build --pull -t "$CI_REGISTRY_IMAGE/toolchain:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/toolchain:$CI_COMMIT_TAG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/toolchain:latest" .
    - docker push "$CI_REGISTRY_IMAGE/toolchain:latest"
  tags:
    - docker
  only:
    - web

.code-quality:
  stage: test
  tags:
    - docker
  image: docker
  allow_failure: true
  variables:
    CI_DEBUG_TRACE: "false"
    REPORT_FORMAT: "json"
  before_script:
    - echo "Skipping 'before_script' part"
  script:
    - echo $REPORT_FORMAT
    - CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID}")
    - VOLUME_PATH=$(docker inspect $CONTAINER_ID --format '{{ range .Mounts }}{{ if eq .Destination "/builds" }}{{ .Source }}{{ end }}{{ end }}')
    - VOLUME_CODE_PATH="${VOLUME_PATH}/${CI_PROJECT_DIR#$CI_BUILDS_DIR}"
    - docker run
        --rm
        --env SOURCE_CODE=$VOLUME_CODE_PATH
        --env REPORT_FORMAT=$REPORT_FORMAT
        --env CODECLIMATE_DEV=1
        --volume /var/run/docker.sock:/var/run/docker.sock
        --volume $VOLUME_CODE_PATH:/code
        registry.gitlab.com/gitlab-org/ci-cd/codequality:latest /code
  artifacts:
    expire_in: 1 week
  dependencies: []

code-quality-json:
  extends: .code-quality
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]

code-quality-html:
  extends: .code-quality
  variables:
    REPORT_FORMAT: "html"
  artifacts:
    paths: [gl-code-quality-report.html]

test-unit:
  stage: test
  needs: ["build-wheel"]
  tags:
    - docker
  script:
    - python tests/test_root_logger.py
    - python tests/test_colorful_output.py
  dependencies:
    - build-wheel

test-version:
  stage: test
  needs: ["build-wheel"]
  tags:
    - docker
  script:
    - python tests/test_version.py
  dependencies:
    - build-wheel
  only:
    - tags

build-docs-for-deploy:
  stage: docs
  needs: ["build-wheel"]
  tags:
    - docker
  variables:
    INCLUDE_CURRENT_BRANCH: '0'
  script:
    - apk add git
    - pip install brest[docs]
    - pip install --no-cache-dir cm/sphinx-versions/sphinx-versions-1.1.3.post3.BR.tar.gz
    - cd docs
    - make html-versioned
  artifacts:
    paths:
      - "docs/_build/html/*"
    expire_in: 1 week
  dependencies:
    - build-wheel
  rules:
    - !reference [.rule-deploy-docs]

build-docs-for-review:
  extends: build-docs-for-deploy
  variables:
    INCLUDE_CURRENT_BRANCH: '1'
  rules:
    - !reference [.rule-do-not-deploy-doc]
    - when: always

build-docs-docker:
  stage: preview
  needs: ["build-docs-for-review"]
  image: docker
  allow_failure: true
  before_script:
    - ''
  tags:
    - docker
  script:
    - docker build --pull -t $IMAGE_TAG -f docs/docker/Dockerfile docs/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  except:
    - tags

.preview:
  stage: preview
  needs: ["build-docs-docker"]
  before_script:
    - ''
  only:
    - branches
  except:
    - master
    - devel
  tags:
    - web

preview:
  extends: .preview
  script:
    - docker stop $PREVIEW_URL || true
    - docker rm $PREVIEW_URL || true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -d --name $PREVIEW_URL --network="web" -l traefik.enable=true -l traefik.http.routers.$ROUTER_ID.rule=Host\(\`$PREVIEW_URL\`\) -l traefik.http.routers.$ROUTER_ID.tls=true --pull=always $DOCKER_ENV $IMAGE_TAG
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    url: https://${CI_COMMIT_REF_SLUG}-${DOC_REVIEW_URL}
    on_stop: stop_preview

stop_preview:
  extends: .preview
  script:
    - docker stop $PREVIEW_URL
    - docker rm $PREVIEW_URL
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    action: stop

staging:
  stage: preview
  needs: ["build-docs-docker"]
  before_script:
    - ''
  script:
    - docker stop $DOC_STAGING_URL || true
    - docker rm $DOC_STAGING_URL || true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -d --name $DOC_STAGING_URL --network="web" -l traefik.enable=true -l traefik.http.routers.$ROUTER_ID.rule=Host\(\`$DOC_STAGING_URL\`\) -l traefik.http.routers.$ROUTER_ID.tls=true --pull=always $DOCKER_ENV $IMAGE_TAG
  environment:
    name: staging
    url: https://${DOC_STAGING_URL}
  only:
    - devel
  except:
    - tags
  tags:
    - web

deploy-wheel:
  stage: deploy
  needs: ["build-wheel", "test-unit", "test-version"]
  tags:
    - docker
  image: ${CI_REGISTRY}/br/toolchains/release:0.1
  before_script:
    - echo "$PYPI_KEY" | tr -d '\r' > ./ssh_key
    - chmod 600 ./ssh_key
  script:
    - |
      sftp -i ./ssh_key -oStrictHostKeyChecking=no $PYPI_USER@$PYPI_HOST:/brest/ << EOF
        put dist/*
        quit
      EOF
  dependencies:
    - build-wheel
  only:
    - tags

deploy-docs:
  stage: deploy
  needs: ["deploy-wheel", "build-docs-for-deploy"]
  tags:
    - docker
  image: ${CI_REGISTRY}/br/toolchains/release:0.1
  allow_failure: true
  before_script:
    - echo "$DOCS_KEY" | tr -d '\r' > ./ssh_key
    - chmod 600 ./ssh_key
  script:
    - |
      sftp -i ./ssh_key -oStrictHostKeyChecking=no $DOCS_USER@$DOCS_HOST:/brest/ << EOF
        put -R docs/_build/html/*
        quit
      EOF
  dependencies:
    - deploy-wheel
    - build-docs-for-deploy
  rules:
    - !reference [.rule-deploy-docs]
