version: 1
formatters:
  base:
    format: '[%(asctime)s][%(levelname)s] : %(class_name)s.%(funcName)s() -> %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: base
    stream: ext://sys.stdout
  console_dbg:
    (): 'brest.log.coloredHandlerFactory'
    level: DEBUG
    formatter: base
loggers:
  brest:
    level: DEBUG
    handlers: [console_dbg]
    propagate: no
root:
  level: DEBUG
  handlers: [console]